### ISSUE TITLE
How to remove empty lines from the output file data display?

### ISSUE THREAD

**Issue by BowieHHY** [jerryshell/clinicaltrials#2]
How to remove empty lines from the output file data display?
![image](https://github.com/jerryshell/clinicaltrials/assets/44061095/bc50f464-d169-495e-bb74-be9550fcf18d)

**Comment by jerryshell** [comment]
fixed in: https://github.com/jerryshell/clinicaltrials/commit/a8753cc02c0ced76b72bfaf9d8266b9299f612d6
